/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'eleven' at '16-9-22 上午9:32' with Gradle 3.0
 *
 * @author eleven, @date 16-9-22 上午9:32
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
